# Generated by Django 5.2.8 on 2025-11-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'OCR Record'},
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the record was created.'),
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='file_size',
            field=models.IntegerField(help_text='Size of the file in bytes.'),
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='filename',
            field=models.CharField(help_text='Original name of the uploaded file.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='ocr_text',
            field=models.TextField(help_text='The extracted text result from the OCR process.'),
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Processing'), ('Processed', 'Successfully Processed'), ('Error', 'Processing Error')], default='Processed', help_text='Processing status.', max_length=50),
        ),
    ]
