# Generated by Django 5.2.8 on 2025-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_alter_ocrrecord_options_alter_ocrrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrecord',
            name='image',
            field=models.ImageField(default='', help_text='The path to the uploaded image file.', upload_to='ocr_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Processing'), ('Processed', 'Successfully Processed'), ('Error', 'Processing Error')], default='Processing', help_text='Processing status.', max_length=50),
        ),
    ]
